### ISSUE TITLE
Feature request: vape as a power bank?

### ISSUE THREAD

**Issue by shola** [ginbot86/ColorLCDVape-RE#10]
I read your blog post and while it has a lot of great info about the display, it doesn’t mention much detail about the charging system. Would it be possible to disable “vaping”, continue to allow charging, and also enable using the vape to charge other devices?

**Comment by ginbot86** [comment]
The charger is quite rudimentary: a simple linear charging IC that burns off excess voltage from the USB port to the battery as heat. It's effective for low charging currents but is still rather inefficient. Switched-mode chargers are way more efficient but are more complex to design (although prebuilt modules do exist online).

Turning the vape into a power bank would require new hardware, as the USB port on the vape's board is configured to be input-only, with no circuitry to boost the small 600mAh battery's voltage to the 5V required to charge another device. Disabling vaping and replacing the space taken up by the vape juice sponge/heater coil with additional battery capacity could be feasible, though.

**Comment by shola** [comment]
Thanks for sharing your research that there are physical limitations that make it impossible to use the usb port to be bidirectional. Much appreciated
